name: xanssh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  dartssh2: ^2.8.2
  xterm: ^3.5.0
  desktop_multi_window: ^0.2.0
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  sqflite_common_ffi: ^2.3.2+1
  encrypt: ^5.0.3
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
